version: "3.7"

services:
  mysql:
    container_name: mysql_for_php
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my_insecure_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  console:
    container_name: console_php
    build:
      context: ./docker/php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app:delegated
  
  php-fpm:
    container_name: php_fpm
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/app:delegated
    depends_on:
      - mysql
    
  nginx:
    container_name: nginx_php
    image: nginx:stable-alpine
    working_dir: /var/www/app
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  phpmyadmin:
    container_name: phpmyadmin_php
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
